EDA

Aqui se realizara el analisis exploratorio de los datos IPM

In [ ]:
%pip install openpyxl

In [ ]:
%pip install matplotlib

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yaml
import openpyxl
import csv

In [ ]:
#Carga de archivos

hogares_ipm_df = pd.read_csv(r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Dataset_Hogares.csv")
display(hogares_ipm_df.head(10))

print("-----------------------------------------------------------------------------------------")

diccionario_datos_df =pd.read_excel(r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Diccionario_de _datos _IPM_2025.xlsx")
display(diccionario_datos_df.head(10))

In [ ]:

#Cargar el CSV original y separar las columnas para la lectura cprrecta del archivo csv

hogares_ipm_df = pd.read_csv(r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Dataset_Hogares.csv",
    sep=",",
    encoding="utf-8",
    quoting=csv.QUOTE_NONE,
    skipinitialspace=True
)

# Revisar las dimensiones y las columnas
print("Dimensiones:", hogares_ipm_df.shape)
print("Cantidad de columnas:", len(hogares_ipm_df.columns))
print("Columnas:", hogares_ipm_df.columns.tolist())

hogares_ipm_df.head()

In [ ]:
#Cargar el diccionario de datos desde la segunda hoja del Excel, ya que aqui estan los significados de las columnas

diccionario_datos_df = pd.read_excel(
    r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Diccionario_datos _IPM_2025.xlsx",
    sheet_name=1,
    engine="openpyxl"
)

# Revisar la estructura del diccionario
print("Dimensiones:", diccionario_datos_df.shape)
print("Columnas:", diccionario_datos_df.columns.tolist())

diccionario_datos_df.head(10)

In [ ]:

#Cargar la segunda hoja sin definir todavía los encabezados
diccionario_datos_df = pd.read_excel(
    r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Diccionario_datos _IPM_2025.xlsx",
    sheet_name=1,
    header=None
)

#Buscar la fila donde aparecen los encabezados
for i, fila in diccionario_datos_df.iterrows():
    valores = fila.astype(str).str.strip().str.lower().tolist()

    if "campo" in valores and "nombre" in valores:
        diccionario_datos_df.columns = diccionario_datos_df.iloc[i]
        diccionario_datos_df = diccionario_datos_df.iloc[i + 1:].reset_index(drop=True)
        break

#Limpiar espacios en los nombres de las columnas
diccionario_datos_df.columns = (
    diccionario_datos_df.columns.astype(str).str.strip()
)

#Eliminar filas sin nombre de variable
diccionario_datos_df = diccionario_datos_df.dropna(subset=["Nombre"])

# Verificar resultado
print("Columnas:", diccionario_datos_df.columns.tolist())
print("Dimensiones:", diccionario_datos_df.shape)

display(diccionario_datos_df.head(10))
print(diccionario_datos_df.info(verbose=True))

In [12]:
print(hogares_ipm_df.info(verbose=True))
print(diccionario_datos_df.info(verbose=True))

<class 'pandas.DataFrame'>
RangeIndex: 276666 entries, 0 to 276665
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   "directorio       276666 non-null  str
 1   ""secuencia_p""   276666 non-null  int64
 2   ""mes""           276666 non-null  int64
 3   ""nper""          276666 non-null  int64
 4   ""npersug""       276666 non-null  int64
 5   ""clase""         276666 non-null  int64
 6   ""ingtotug""      276666 non-null  float64
 7   ""dominio""       276666 non-null  str
 8   ""lp""            276666 non-null  float64
 9   ""li""            276666 non-null  float64
 10  ""p5090""         276666 non-null  int64
 11  ""p5100""         9241 non-null    float64
 12  ""p5130""         164614 non-null  float64
 13  ""ingtotarr""     276666 non-null  float64
 14  ""ingpcug""       276666 non-null  float64
 15  ""pobre""         276666 non-null  int64
 16  ""indigente""     276666 non-null  int64
 17  ""npobres""       276666 non-null  int64
 18  ""nindigentes""   276666 non-null  int64
 19  ""fex_c""         276666 non-null  float64
 20  ""ciudad_sinam""  276666 non-null  str
 21  ""dpto""          276666 non-null  str
 22  ""fex_dpto"""     276666 non-null  str
dtypes: float64(8), int64(10), str(5)
memory usage: 48.5 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Campo        23 non-null     object
 1   Nombre       23 non-null     str
 2   Descripción  23 non-null     str
 3   Valor        21 non-null     str
 4   var_txt      13 non-null     str
dtypes: object(1), str(4)
memory usage: 1.0+ KB
None

In [13]:
hogares_ipm_df['""ciudad_sinam""'].nunique()
hogares_ipm_df['""ciudad_sinam""'].value_counts()

""ciudad_sinam""
""""                 92298
""MEDELLIN""          9746
""BOGOTA""            9733
""MANIZALES""         9655
""PEREIRA""           9394
""ARMENIA""           9233
""PASTO""             8900
""CARTAGENA""         8844
""VILLAVICENCIO""     8440
""CALI""              8384
""QUIBDO""            8305
""FLORENCIA""         8021
""POPAYAN""           8006
""TUNJA""             7929
""SANTA MARTA""       7865
""NEIVA""             7797
""BUCARAMANGA""       7466
""CUCUTA""            7265
""SINCELEJO""         6931
""VALLEDUPAR""        6765
""IBAGUE""            6711
""BARRANQUILLA""      6575
""RIOHACHA""          6485
""MONTERIA""          5918
Name: count, dtype: int64

In [14]:
hogares_ipm_df['""dpto""'].nunique()
hogares_ipm_df['""dpto""'].value_counts()

""dpto""
""Antioquia""             17764
""Valle del Cauca""       15545
""Caldas""                15047
""Risaralda""             14473
""Santander""             14049
""Nariño""                13465
""Quindío""               12626
""Meta""                  12177
""Bolívar""               11237
""Caquetá""               11178
""Magdalena""             11142
""Huila""                 10890
""Chocó""                 10859
""Cauca""                 10856
""Boyacá""                10736
""Norte de Santander""    10631
""Atlántico""             10580
""Tolima""                10068
""Sucre""                 10065
""Bogotá D.C.""            9733
""La Guajira""             9592
""Cesar""                  9550
""Córdoba""                8251
""Cundinamarca""           6152
Name: count, dtype: int64

In [15]:
hogares_ipm_df['""dominio""'].nunique()
hogares_ipm_df['""dominio""'].value_counts()

""dominio""
""RESTO URBANO""     43675
""RURAL""            37256
""MEDELLIN""         11825
""MANIZALES""        11639
""PEREIRA""          11179
""CALI""             10150
""BOGOTA""            9733
""ARMENIA""           9233
""PASTO""             8900
""BUCARAMANGA""       8900
""CARTAGENA""         8844
""VILLAVICENCIO""     8440
""QUIBDO""            8305
""CUCUTA""            8220
""FLORENCIA""         8021
""POPAYAN""           8006
""BARRANQUILLA""      7939
""TUNJA""             7929
""SANTA MARTA""       7865
""NEIVA""             7797
""SINCELEJO""         6931
""VALLEDUPAR""        6765
""IBAGUE""            6711
""RIOHACHA""          6485
""MONTERIA""          5918
Name: count, dtype: int64

In [ ]:
#Identificar valores nulos
print(hogares_ipm_df.isnull().sum())
#Imputar datos
hogares_ipm_df['""p5100""'].fillna(0,inplace=True)

"directorio              0
""secuencia_p""          0
""mes""                  0
""nper""                 0
""npersug""              0
""clase""                0
""ingtotug""             0
""dominio""              0
""lp""                   0
""li""                   0
""p5090""                0
""p5100""           267425
""p5130""           112052
""ingtotarr""            0
""ingpcug""              0
""pobre""                0
""indigente""            0
""npobres""              0
""nindigentes""          0
""fex_c""                0
""ciudad_sinam""         0
""dpto""                 0
""fex_dpto"""            0
dtype: int64

C:\Users\juan\AppData\Local\Temp\ipykernel_16312\3366274332.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  hogares_ipm_df['""p5100""'].fillna(0,inplace=True)
C:\Users\juan\AppData\Local\Temp\ipykernel_16312\3366274332.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  hogares_ipm_df['""p5130""'].fillna(0,inplace=True)

0         350000.0
1         200000.0
2         300000.0
3         300000.0
4         300000.0
            ...
276661    600000.0
276662    400000.0
276663    500000.0
276664    600000.0
276665    700000.0
Name: ""p5130"", Length: 276666, dtype: float64

In [21]:
#Identificar valores nulos
print(hogares_ipm_df.isnull().sum())
#Imputar datos
hogares_ipm_df['""p5130""'].fillna(0,inplace=True)

"directorio              0
""secuencia_p""          0
""mes""                  0
""nper""                 0
""npersug""              0
""clase""                0
""ingtotug""             0
""dominio""              0
""lp""                   0
""li""                   0
""p5090""                0
""p5100""           267425
""p5130""           112052
""ingtotarr""            0
""ingpcug""              0
""pobre""                0
""indigente""            0
""npobres""              0
""nindigentes""          0
""fex_c""                0
""ciudad_sinam""         0
""dpto""                 0
""fex_dpto"""            0
dtype: int64

C:\Users\juan\AppData\Local\Temp\ipykernel_16312\61045884.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  hogares_ipm_df['""p5130""'].fillna(0,inplace=True)

0         350000.0
1         200000.0
2         300000.0
3         300000.0
4         300000.0
            ...
276661    600000.0
276662    400000.0
276663    500000.0
276664    600000.0
276665    700000.0
Name: ""p5130"", Length: 276666, dtype: float64

In [ ]:
#Identificador de duplicados
print(hogares_ipm_df.duplicated().sum())

0

In [ ]:
#Corregir el nombre de la primera columna
diccionario_datos_df = diccionario_datos_df.rename(
    columns={"8": "Campo", 8: "Campo"}
)

#Si quedaron encabezados duplicados, asignar los nombres correctos
diccionario_datos_df.columns = [
    "Campo", "Nombre", "Descripción", "Valor", "var_txt"
]

#Convertir Campo a numérico y eliminar filas sin Nombre
diccionario_datos_df["Campo"] = pd.to_numeric(
    diccionario_datos_df["Campo"], errors="coerce"
)

diccionario_datos_df = diccionario_datos_df.dropna(
    subset=["Nombre"]
).reset_index(drop=True)

display(diccionario_datos_df.head(10))

In [ ]:

#Cargar la segunda hoja del diccionario
diccionario_datos_df = pd.read_excel( r"C:\Users\juan\Desktop\Trabajo final GA\data\bronze\Diccionario_de _datos _IPM_2025.xlsx",
    sheet_name=1,
    header=None
)

#Buscar la fila que contiene los encabezados
for i, fila in diccionario_datos_df.iterrows():
    valores = fila.astype(str).str.strip().str.lower().tolist()

    if "campo" in valores and "nombre" in valores:
        encabezados = valores
        diccionario_datos_df.columns = (
            fila.astype(str).str.strip().tolist()
        )
        diccionario_datos_df = diccionario_datos_df.iloc[i + 1:].copy()
        break

#Limpiar nombres de columnas
diccionario_datos_df.columns = (
    diccionario_datos_df.columns.astype(str).str.strip()
)

#Conservar las cinco columnas del diccionario
diccionario_datos_df = diccionario_datos_df[
    ["Campo", "Nombre", "Descripción", "Valor", "var_txt"]
].copy()

#Organizar los registros
diccionario_datos_df = diccionario_datos_df.dropna(
    subset=["Nombre"]
).reset_index(drop=True)

#Convertir el campo a número
diccionario_datos_df["Campo"] = pd.to_numeric(
    diccionario_datos_df["Campo"], errors="coerce"
)

display(diccionario_datos_df.head(10))

In [ ]:

#Limpiar nombres de las columnas
diccionario_datos_df.columns = (
    diccionario_datos_df.columns.astype(str).str.strip()
)

#Limpiar espacios en las columnas de texto
for columna in ["Nombre", "Descripción", "Valor", "var_txt"]:
    diccionario_datos_df[columna] = (
        diccionario_datos_df[columna]
        .astype("string")
        .str.strip()
    )

#Eliminar filas sin nombre de variable
diccionario_datos_df = diccionario_datos_df.dropna(
    subset=["Nombre"]
)

#Revisar registros duplicados
print(
    "Registros duplicados:",
    diccionario_datos_df.duplicated(subset=["Nombre"]).sum()
)

display(diccionario_datos_df.head())

In [28]:

#Limpiar los nombres de las columnas del CSV
hogares_ipm_df.columns = (
    hogares_ipm_df.columns
    .str.replace('"', '', regex=False)
    .str.strip()
)

print(hogares_ipm_df.columns.tolist())

['directorio', 'secuencia_p', 'mes', 'nper', 'npersug', 'clase', 'ingtotug', 'dominio', 'lp', 'li', 'p5090', 'p5100', 'p5130', 'ingtotarr', 'ingpcug', 'pobre', 'indigente', 'npobres', 'nindigentes', 'fex_c', 'ciudad_sinam', 'dpto', 'fex_dpto']

In [29]:

# Revisar las variables registradas en el diccionario
display(
    diccionario_datos_df[
        ["Campo", "Nombre", "Descripción"]
    ].head(15)
)

# Comparar las columnas de la base con los campos del diccionario
columnas_base = set(hogares_ipm_df.columns.str.upper().str.strip())

campos_diccionario = set(
    diccionario_datos_df["Campo"]
    .dropna()
    .astype(str)
    .str.replace('"', "", regex=False)
    .str.strip()
    .str.upper()
)

coinciden = columnas_base.intersection(campos_diccionario)

print("Columnas de la base:", len(columnas_base))
print("Campos del diccionario:", len(campos_diccionario))
print("Variables que coinciden:", len(coinciden))
print("Ejemplos de coincidencias:", sorted(coinciden)[:20])

8  Campo        Nombre                                        Descripción
0      1    directorio                                     Llave vivienda
1      2   secuencia_p                                        Llave hogar
2      3           mes                                                Mes
3      4         clase                                              Clase
4      5       dominio                                            Dominio
5      6  ciudad_sinam                      Ciudades capitales (sin A.M.)
6      7         p5090             La vivienda ocupada por este hogar es:
7      8         p5100  ¿Cuánto pagan mensualmente por cuota de amorti...
8      9         p5130  Si tuviera que pagar arriendo por esta viviend...
9     10          nper                               Personas en el hogar
10    11       npersug           Número de personas en la unidad de gasto
11    12      ingtotug  Ingreso total de la unidad de gasto antes de i...
12    13     ingtotarr  Ingreso total de la unidad de gasto con imputa...
13    14       ingpcug  Ingreso percápita de la unidad de gasto con im...
14    15            li                                Línea de indigencia

Columnas de la base: 23
Campos del diccionario: 23
Variables que coinciden: 0
Ejemplos de coincidencias: []

In [31]:

# Crear una copia de la base original
hogares_ipm_descriptivo_df = hogares_ipm_df.copy()

# Normalizar los nombres para relacionarlos
hogares_ipm_descriptivo_df.columns = (
    hogares_ipm_descriptivo_df.columns.astype(str).str.strip().str.lower()
)

diccionario_datos_df["Nombre"] = (
    diccionario_datos_df["Nombre"].astype("string").str.strip().str.lower()
)

diccionario_datos_df["Descripción"] = (
    diccionario_datos_df["Descripción"].astype("string").str.strip()
)

# Crear el diccionario: nombre original -> descripción
renombrar_columnas = (
    diccionario_datos_df
    .dropna(subset=["Nombre", "Descripción"])
    .drop_duplicates(subset=["Nombre"])
    .set_index("Nombre")["Descripción"]
    .to_dict()
)

# Renombrar solo las columnas que tengan descripción disponible
hogares_ipm_descriptivo_df = hogares_ipm_descriptivo_df.rename(
    columns=renombrar_columnas
)

# Mostrar el resultado
print("Dimensiones de la base:", hogares_ipm_descriptivo_df.shape)
print("\nColumnas descriptivas:")
print(hogares_ipm_descriptivo_df.columns.tolist())

display(hogares_ipm_descriptivo_df.head())

Dimensiones de la base: (276666, 23)

Columnas descriptivas:
['Llave vivienda', 'Llave hogar', 'Mes', 'Personas en el hogar', 'Número de personas en la unidad de gasto', 'Clase', 'Ingreso total de la unidad de gasto antes de imputación de arriendo a propietarios y usufructuarios', 'Dominio', 'Línea de pobreza', 'Línea de indigencia', 'La vivienda ocupada por este hogar es:', '¿Cuánto pagan mensualmente por cuota de amortización?', 'Si tuviera que pagar arriendo por esta vivienda, ¿cuánto estima que tendría que pagar mensualmente?', 'Ingreso total de la unidad de gasto con imputación de arriendo a propietarios y usufructuarios', 'Ingreso percápita de la unidad de gasto con imputación de arriendo a propietarios y usufructuarios', 'Pobre', 'Indigente', 'Número de pobres', 'Número de Indigentes', 'Factor de expansión anualizado', 'Ciudades capitales (sin A.M.)', 'Departamento', 'Factor de expansión departamental']

,Llave vivienda,Llave hogar,Mes,Personas en el hogar,Número de personas en la unidad de gasto,Clase,Ingreso total de la unidad de gasto antes de imputación de arriendo a propietarios y usufructuarios,Dominio,Línea de pobreza,Línea de indigencia,...,Ingreso total de la unidad de gasto con imputación de arriendo a propietarios y usufructuarios,Ingreso percápita de la unidad de gasto con imputación de arriendo a propietarios y usufructuarios,Pobre,Indigente,Número de pobres,Número de Indigentes,Factor de expansión anualizado,Ciudades capitales (sin A.M.),Departamento,Factor de expansión departamental
0,"""8086872",1,1,1,1,2,1.040000e+06,"""""RURAL""""",308654.56309,182935.52974,...,1.390000e+06,1.390000e+06,0,0,0,0,182.062690,"""""""""","""""Bolívar""""","80.3363199365037"""
1,"""8086874",1,1,3,3,2,2.320833e+06,"""""RURAL""""",308654.56309,182935.52974,...,2.520833e+06,8.402778e+05,0,0,0,0,100.707518,"""""""""","""""Bolívar""""","64.5734962006178"""
2,"""8086875",1,1,1,1,2,2.784000e+06,"""""RURAL""""",308654.56309,182935.52974,...,3.084000e+06,3.084000e+06,0,0,0,0,175.342825,"""""""""","""""Bolívar""""","68.9995596863"""
3,"""8086876",1,1,3,3,2,2.686667e+06,"""""RURAL""""",308654.56309,182935.52974,...,2.986667e+06,9.955556e+05,0,0,0,0,201.672077,"""""""""","""""Bolívar""""","145.284264410861"""
4,"""8086877",1,1,3,3,2,3.385333e+06,"""""RURAL""""",308654.56309,182935.52974,...,3.685333e+06,1.228444e+06,0,0,0,0,208.939282,"""""""""","""""Bolívar""""","122.440831170849"""